import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

/** Runs the real Python agent. Requires the project's .venv, so this works in local
 *  development and anywhere the Python environment is present. The preset answers on
 *  the landing page are pre-generated by the same code path, so the deployed page
 *  still shows genuine pipeline output when Python is not available.
 *
 *  The response is an event stream, not one JSON body. A run takes about ninety seconds,
 *  and the agent writes each reasoning step to stderr as `@progress {json}` the moment it
 *  happens. Forwarding those lets the interface show the loop working rather than a dead
 *  button for a minute and a half. The final event carries the answer. */

export const maxDuration = 300;

const ROOT = resolve(process.cwd(), "..");
const PYTHON = join(ROOT, ".venv", "bin", "python");
const SCRIPT = join(ROOT, "scripts", "ask.py");

const PROGRESS_PREFIX = "@progress ";

export async function POST(request: Request) {
  let question = "";
  try {
    ({ question } = await request.json());
  } catch {
    return Response.json({ error: "invalid JSON body" }, { status: 400 });
  }

  question = (question ?? "").trim();
  if (!question) return Response.json({ error: "question is required" }, { status: 400 });
  if (question.length > 400) {
    return Response.json({ error: "question too long" }, { status: 400 });
  }

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (event: string, data: unknown) => {
        controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));
      };

      const dir = await mkdtemp(join(tmpdir(), "mission-control-"));
      const outPath = join(dir, "answer.json");

      try {
        // The question is passed as a separate argv entry, never interpolated into a
        // shell string, and no shell is spawned.
        const child = spawn(PYTHON, [SCRIPT, question, "--json", outPath], {
          cwd: ROOT,
          stdio: ["ignore", "ignore", "pipe"],
        });

        let errors = "";
        let pending = "";

        child.stderr.on("data", (chunk) => {
          pending += String(chunk);
          const lines = pending.split("\n");
          // Keep the trailing fragment: a write can split mid-line.
          pending = lines.pop() ?? "";
          for (const line of lines) {
            if (line.startsWith(PROGRESS_PREFIX)) {
              try {
                send("progress", JSON.parse(line.slice(PROGRESS_PREFIX.length)));
              } catch {
                // A malformed progress line is not worth failing a run over.
              }
            } else if (line.trim()) {
              errors += `${line}\n`;
            }
          }
        });

        const exit = await new Promise<number>((done, fail) => {
          child.on("error", fail);
          child.on("close", (code) => done(code ?? 0));
        });

        if (exit !== 0) {
          throw new Error(errors.trim().slice(-1200) || `agent exited ${exit}`);
        }

        send("result", JSON.parse(await readFile(outPath, "utf8")));
      } catch (error) {
        send("error", { error: error instanceof Error ? error.message : String(error) });
      } finally {
        await rm(dir, { recursive: true, force: true });
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    },
  });
}
